excluded:  # 執行 linting 時忽略的路徑。 優先順序比 `included` 更高。
  - Pods

disabled_rules: # 執行時排除掉的規則
  - trailing_whitespace   # 每一個空行不能有空格，會與Xcode換行後自動對齊生成的空格衝突，建議排除掉
  - unused_closure_parameter
  - switch_case_alignment

